### ISSUE TITLE
Audio Support for NoVNC

### ISSUE THREAD

**Issue by saschazesiger** [ich777/docker-novnc-baseimage#2]
I was wondering if it would be possible to add sound support to your NoNVC repositories... I think it would be a great addition to your project and would be helpful to many users.

Recently, someone posted a solution for implementing audio in NoVNC in the repository https://github.com/no-body-in-particular/NoVNCAudio and there is a similar example in the repository https://github.com/DomiStyle/docker-tor-browser/tree/vlc

**Comment by ich777** [comment]
No, I won‘t do/add that because VNC is not designed to support sound and everything else are hacky workarounds wich doesn‘t always work.
I really don‘t want to add something that doesn‘t work reliably.
